# TASK WEBFORM - INFORMED CONSENT
uuid: 16728818-2f4a-4853-ae28-596094fa9571
langcode: en
status: open
dependencies: {  }
weight: 0
open: null
close: null
uid: 1
template: false
archive: false
id: t1_nct123
title: 'Task: Informed Consent'
description: 'Study: nct123 / Webform: t1_nct123'
categories:
  - Task
elements: |-
  placeholder_for_expand_collapse:
    '#type': details
    '#title': placeholder_for_expand_collapse
    '#title_display': invisible
    '#states':
      invisible:
        - ':input[name="step_1"]':
            checked: true
        - or
        - ':input[name="step_1"]':
            unchecked: true
    '#access_create_roles':
      - authenticated
    '#access_update_roles':
      - authenticated
    '#access_view_roles':
      - authenticated

  step_1:
    '#type': checkbox
    '#title': 'Step 1 - Obtain Informed Consent'
    '#wrapper_attributes':
      class:
        - step-header
  step1_details:
    '#type': details
    '#title': Details
    '#title_display': invisible
    '#attributes':
      class:
        - step-content
    step1_instructions:
      '#type': processed_text
      '#text': '<div id="container" class="step-detail"><div id="definition" class="step-detail-definition"><ul><li>Explain the study details, including purpose, procedures, risks, and benefits to the patient</li><li>Obtain informed consent from the patient, ensuring they understand and agree to the study terms</li><li>[Optional] Discuss with the patient about the possibility of using their data for future research</li></ul></div><div id="references" class="step-detail-list"><div class="step-detail-header">REFERENCES</div><ul><li><a href="https://clintegrate.s3.amazonaws.com/documents/NCT02702401/NCT02702401+Protocol.pdf#page=65" target="_blank">Protocol - Consent Definition</a><img src="../themes/custom/sitehub_material_base/images/link.png" /></li><li><a href="https://clintegrate.s3.amazonaws.com/documents/NCT02702401/NCT02702401+Protocol.pdf#page=29" target="_blank">Protocol - Inclusion/Exclusion Criteria</a><img src="../themes/custom/sitehub_material_base/images/link.png" /></li><li><a href="https://clintegrate.s3.amazonaws.com/documents/NCT02702401/NCT02702401+PCH.pdf" target="_blank">Consent Form</a><img src="../themes/custom/sitehub_material_base/images/link.png" /></li><li><a href="https://www.hhs.gov/ohrp/regulations-and-policy/guidance/research-use-of-data/index.html" target="_blank">Guidance on Research Use of Data</a><img src="../themes/custom/sitehub_material_base/images/link.png" /></li></ul></div><div id="people" class="step-detail-list"><div class="step-detail-header">PEOPLE</div><ul><li><a href="mailto:pbellweather@mail.com" target="_blank">Patricia Bellweather</a><img src="../themes/custom/sitehub_material_base/images/email.png" /><span>509.555.3419</span><img src="../themes/custom/sitehub_material_base/images/phone.png" /><span>Patient Recruiter</span></li></ul></div></div>'
      '#format': full_html

  step_2:
    '#type': checkbox
    '#title': 'Step 2 - Record Consent Decision'
    '#wrapper_attributes':
      class:
        - step-header
  step2_details:
    '#type': details
    '#title': Details
    '#title_display': invisible
    '#attributes':
      class:
        - step-content
    step2_instructions:
      '#type': processed_text
      '#text': '<div id="container" class="step-detail"><div id="definition" class="step-detail-definition"><ul><li>File the signed consent form in the patients clinical study folder</li><li>Scan the signed consent form into the EHR system</li><li>Record the signed consent into the EDC system</li></ul></div><div id="references" class="step-detail-list"><div class="step-detail-header">REFERENCES</div><ul><li><a href="https://clintegrate.s3.amazonaws.com/documents/NCT02702401/NCT02702401+Record_Keeping.pdf" target="_blank">Record Keeping Guidelines</a><img src="../themes/custom/sitehub_material_base/images/link.png" /></li><li><a href="https://clintegrate.s3.amazonaws.com/ehr-app/login.html" target="_blank">Epic EHR</a><img src="../themes/custom/sitehub_material_base/images/link.png" /></li><li><a href="https://clintegrate.s3.amazonaws.com/edc-app/login.html?section=consent" target="_blank">Medidata EDC</a><img src="../themes/custom/sitehub_material_base/images/link.png" /></li></ul></div></div'
      '#format': full_html

  step_3:
    '#type': checkbox
    '#title': 'Step 3 - Inform Internal Medical Personnel'
    '#wrapper_attributes':
      class:
        - step-header
  step3_details:
    '#type': details
    '#title': Details
    '#title_display': invisible
    '#attributes':
      class:
        - step-content
    step3_instructions:
      '#type': processed_text
      '#text': '<div id="container" class="step-detail"><div id="definition" class="step-detail-definition"><ul><li>Email Patricia with the result of the consent</li><li>Inform Rachel and Mark about the patient consent</li></ul></div><div id="people" class="step-detail-list"><div class="step-detail-header">PEOPLE</div><ul><li><a href="mailto:pbellweather@mail.com" target="_blank">Patricia Bellweather</a><img src="../themes/custom/sitehub_material_base/images/email.png" /><span>509.555.3419</span><img src="../themes/custom/sitehub_material_base/images/phone.png" /><span>Patient Recruiter</span></li><li><a href="mailto:rauchliffe@mail.com" target="_blank">Rachel Auchliffe</a><img src="../themes/custom/sitehub_material_base/images/email.png" /><span>957.555.2323</span><img src="../themes/custom/sitehub_material_base/images/phone.png" /><span>Site Rater</span></li><li><a href="mailto:mdavis@mail.com" target="_blank">Mark Davis</a><img src="../themes/custom/sitehub_material_base/images/email.png" /><span>Clinical Trial Administrator</span></li></ul></div></div>'
      '#format': full_html

  submit_buttons:
    '#type': webform_flexbox
    complete:
      '#type': webform_actions
      '#title': 'Complete Now'
      '#flex': 0
      '#attributes':
        class:
          - task-primary-button
      '#submit__label': 'Complete Now'
      '#update__label': 'Complete Now'
    complete_later:
      '#type': webform_actions
      '#title': 'Complete Later'
      '#flex': 0
      '#attributes':
        class:
          - task-secondary-button
      '#submit__label': 'Complete Later'
      '#update__label': 'Complete Later'
css: ''
javascript: ''
settings:
  ajax: false
  ajax_scroll_top: form
  ajax_progress_type: ''
  ajax_effect: ''
  ajax_speed: null
  page: true
  page_submit_path: ''
  page_confirm_path: ''
  page_theme_name: ''
  form_title: source_entity_webform
  form_submit_once: true
  form_open_message: ''
  form_close_message: ''
  form_exception_message: ''
  form_previous_submissions: false
  form_confidential: false
  form_confidential_message: ''
  form_disable_remote_addr: false
  form_convert_anonymous: false
  form_prepopulate: false
  form_prepopulate_source_entity: false
  form_prepopulate_source_entity_required: false
  form_prepopulate_source_entity_type: ''
  form_unsaved: false
  form_disable_back: true
  form_submit_back: false
  form_disable_autocomplete: false
  form_novalidate: false
  form_disable_inline_errors: false
  form_required: false
  form_autofocus: false
  form_details_toggle: false
  form_reset: false
  form_access_denied: default
  form_access_denied_title: ''
  form_access_denied_message: ''
  form_access_denied_attributes: {  }
  form_file_limit: ''
  form_attributes: {  }
  form_method: ''
  form_action: ''
  share: false
  share_node: false
  share_theme_name: ''
  share_title: true
  share_page_body_attributes: {  }
  submission_label: ''
  submission_exception_message: ''
  submission_locked_message: ''
  submission_log: false
  submission_excluded_elements: {  }
  submission_exclude_empty: false
  submission_exclude_empty_checkbox: false
  submission_views: {  }
  submission_views_replace: {  }
  submission_user_columns: {  }
  submission_user_duplicate: false
  submission_access_denied: default
  submission_access_denied_title: ''
  submission_access_denied_message: ''
  submission_access_denied_attributes: {  }
  previous_submission_message: ''
  previous_submissions_message: ''
  autofill: false
  autofill_message: ''
  autofill_excluded_elements: {  }
  wizard_progress_bar: true
  wizard_progress_pages: false
  wizard_progress_percentage: false
  wizard_progress_link: false
  wizard_progress_states: false
  wizard_start_label: ''
  wizard_preview_link: false
  wizard_confirmation: true
  wizard_confirmation_label: ''
  wizard_auto_forward: true
  wizard_auto_forward_hide_next_button: false
  wizard_keyboard: true
  wizard_track: ''
  wizard_prev_button_label: ''
  wizard_next_button_label: ''
  wizard_toggle: false
  wizard_toggle_show_label: ''
  wizard_toggle_hide_label: ''
  wizard_page_type: container
  wizard_page_title_tag: h2
  preview: 0
  preview_label: ''
  preview_title: ''
  preview_message: ''
  preview_attributes: {  }
  preview_excluded_elements: {  }
  preview_exclude_empty: true
  preview_exclude_empty_checkbox: false
  draft: none
  draft_multiple: false
  draft_auto_save: false
  draft_saved_message: ''
  draft_loaded_message: ''
  draft_pending_single_message: ''
  draft_pending_multiple_message: ''
  confirmation_type: page
  confirmation_url: ''
  confirmation_title: ''
  confirmation_message: ''
  confirmation_attributes: {  }
  confirmation_back: true
  confirmation_back_label: ''
  confirmation_back_attributes: {  }
  confirmation_exclude_query: false
  confirmation_exclude_token: false
  confirmation_update: false
  limit_total: null
  limit_total_interval: null
  limit_total_message: ''
  limit_total_unique: false
  limit_user: null
  limit_user_interval: null
  limit_user_message: ''
  limit_user_unique: false
  entity_limit_total: null
  entity_limit_total_interval: null
  entity_limit_user: null
  entity_limit_user_interval: null
  purge: none
  purge_days: null
  results_disabled: false
  results_disabled_ignore: false
  results_customize: false
  token_view: false
  token_update: false
  token_delete: false
  serial_disabled: false
access:
  create:
    roles:
      - authenticated
    users: {  }
    permissions: {  }
  view_any:
    roles:
      - authenticated
    users: {  }
    permissions: {  }
  update_any:
    roles:
      - authenticated
    users: {  }
    permissions: {  }
  delete_any:
    roles:
      - authenticated
    users: {  }
    permissions: {  }
  purge_any:
    roles: {  }
    users: {  }
    permissions: {  }
  view_own:
    roles: {  }
    users: {  }
    permissions: {  }
  update_own:
    roles: {  }
    users: {  }
    permissions: {  }
  delete_own:
    roles: {  }
    users: {  }
    permissions: {  }
  administer:
    roles: {  }
    users: {  }
    permissions: {  }
  test:
    roles: {  }
    users: {  }
    permissions: {  }
  configuration:
    roles: {  }
    users: {  }
    permissions: {  }
handlers: {  }
variants: {  }